from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime

from app import models
from app.auth import get_current_user
from app.database import get_db

router = APIRouter(prefix="/api/reports", tags=["reports"])

EMISSION_FACTOR = 0.82

# ── Brand Colors ──────────────────────────────────────────────
C_NAVY    = colors.HexColor("#0f172a")
C_CYAN    = colors.HexColor("#0284c7")
C_GREEN   = colors.HexColor("#059669")
C_AMBER   = colors.HexColor("#d97706")
C_RED     = colors.HexColor("#dc2626")
C_SLATE   = colors.HexColor("#475569")
C_LIGHT   = colors.HexColor("#f1f5f9")
C_BORDER  = colors.HexColor("#e2e8f0")
C_WHITE   = colors.white

MONTHS = ["", "January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]
MONTHS_SHORT = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


# ── Style helpers ─────────────────────────────────────────────
def _styles():
    base = getSampleStyleSheet()
    return {
        "brand":    ParagraphStyle("brand",    fontSize=9,  textColor=C_CYAN,  alignment=TA_CENTER, fontName="Helvetica"),
        "title":    ParagraphStyle("title",    fontSize=22, textColor=C_NAVY,  alignment=TA_CENTER, fontName="Helvetica-Bold", spaceAfter=2),
        "subtitle": ParagraphStyle("subtitle", fontSize=9,  textColor=C_SLATE, alignment=TA_CENTER, fontName="Helvetica"),
        "h2":       ParagraphStyle("h2",       fontSize=13, textColor=C_NAVY,  fontName="Helvetica-Bold", spaceBefore=14, spaceAfter=6),
        "h3":       ParagraphStyle("h3",       fontSize=10, textColor=C_CYAN,  fontName="Helvetica-Bold", spaceBefore=8,  spaceAfter=4),
        "body":     ParagraphStyle("body",     fontSize=9,  textColor=C_SLATE, fontName="Helvetica", leading=14, spaceAfter=3),
        "bold":     ParagraphStyle("bold",     fontSize=9,  textColor=C_NAVY,  fontName="Helvetica-Bold", leading=14),
        "small":    ParagraphStyle("small",    fontSize=8,  textColor=C_SLATE, fontName="Helvetica", alignment=TA_CENTER),
        "kpi_val":  ParagraphStyle("kpi_val",  fontSize=18, textColor=C_NAVY,  fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=2),
        "kpi_lbl":  ParagraphStyle("kpi_lbl",  fontSize=7,  textColor=C_SLATE, fontName="Helvetica",      alignment=TA_CENTER, textTransform="uppercase"),
    }


def _page_fn(canvas, doc):
    """Branded header/footer on every page."""
    w, h = A4
    canvas.saveState()
    # Top accent bar
    canvas.setFillColor(C_CYAN)
    canvas.rect(0, h - 8*mm, w, 8*mm, fill=1, stroke=0)
    canvas.setFillColor(C_WHITE)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(18*mm, h - 5.5*mm, "EnergiAudit")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(w - 18*mm, h - 5.5*mm,
                           f"CONFIDENTIAL  |  Generated {datetime.now().strftime('%d %b %Y')}")
    # Bottom accent bar
    canvas.setFillColor(C_LIGHT)
    canvas.rect(0, 0, w, 12*mm, fill=1, stroke=0)
    canvas.setFillColor(C_SLATE)
    canvas.setFont("Helvetica", 7.5)
    canvas.drawCentredString(w / 2, 4*mm,
        "This document is system-generated by the EnergiAudit Platform.  "
        "For queries contact support@energiaudit.in")
    canvas.setFont("Helvetica", 7.5)
    canvas.drawRightString(w - 18*mm, 4*mm, f"Page {doc.page}")
    canvas.restoreState()


def _build_pdf(title: str, subtitle: str, sections: list) -> BytesIO:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            topMargin=22*mm, bottomMargin=18*mm,
                            leftMargin=18*mm, rightMargin=18*mm)
    s = _styles()
    story = [
        Spacer(1, 4*mm),
        Paragraph(title,    s["title"]),
        Paragraph(subtitle, s["subtitle"]),
        Spacer(1, 3*mm),
        HRFlowable(width="100%", thickness=1.5, color=C_CYAN, spaceAfter=8),
    ]
    for section in sections:
        story.extend(section)
        story.append(Spacer(1, 6))
    doc.build(story, onFirstPage=_page_fn, onLaterPages=_page_fn)
    buf.seek(0)
    return buf


def _kpi_box(label: str, value: str, unit: str = "", accent=None) -> Table:
    """Single KPI cell for a metrics row."""
    accent = accent or C_CYAN
    s = _styles()
    cell = Table([[
        Paragraph(value, s["kpi_val"]),
        Paragraph(f"{unit}<br/><font size='7' color='#475569'>{label}</font>",
                  ParagraphStyle("kv", fontSize=8, textColor=accent,
                                 fontName="Helvetica-Bold", alignment=TA_CENTER))
    ]], colWidths=None)
    return cell


def _kpi_row(items: list) -> Table:
    """Row of KPI boxes: items = [(label, value, unit, accent_color), ...]"""
    s = _styles()
    n = len(items)
    col_w = (A4[0] - 36*mm) / n

    cells = []
    for label, value, unit, accent_c in items:
        c = colors.HexColor(accent_c) if isinstance(accent_c, str) else accent_c
        cells.append([
            Paragraph(value, ParagraphStyle("kv2", fontSize=16, textColor=C_NAVY,
                                            fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=1)),
            Paragraph(unit,  ParagraphStyle("ku",  fontSize=7,  textColor=c,
                                            fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=1)),
            Paragraph(label, ParagraphStyle("kl",  fontSize=7,  textColor=C_SLATE,
                                            fontName="Helvetica",      alignment=TA_CENTER)),
        ])

    row_data = [[Table([[c[0]], [c[1]], [c[2]]], colWidths=[col_w - 8*mm]) for c in cells]]
    tbl = Table(row_data, colWidths=[col_w] * n)
    tbl.setStyle(TableStyle([
        ("BOX",        (0, 0), (-1, -1), 0.5, C_BORDER),
        ("INNERGRID",  (0, 0), (-1, -1), 0.5, C_BORDER),
        ("BACKGROUND", (0, 0), (-1, -1), C_LIGHT),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
    ]))
    return tbl


def _data_table(headers: list, rows: list, col_widths=None, highlight_col=None) -> Table:
    s = _styles()
    header_cells = [Paragraph(h, ParagraphStyle("th", fontSize=8, textColor=C_WHITE,
                                                fontName="Helvetica-Bold", alignment=TA_CENTER))
                    for h in headers]
    body_cells = [[Paragraph(str(cell), ParagraphStyle("td", fontSize=8.5, textColor=C_NAVY,
                                                        fontName="Helvetica", alignment=TA_CENTER))
                   for cell in row] for row in rows]

    data = [header_cells] + body_cells
    tbl = Table(data, colWidths=col_widths, repeatRows=1)
    style = [
        ("BACKGROUND",    (0, 0), (-1, 0),  C_NAVY),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  C_WHITE),
        ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0),  8),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [C_WHITE, C_LIGHT]),
        ("GRID",          (0, 0), (-1, -1), 0.4, C_BORDER),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]
    if highlight_col is not None:
        style.append(("TEXTCOLOR", (highlight_col, 1), (highlight_col, -1), C_GREEN))
        style.append(("FONTNAME",  (highlight_col, 1), (highlight_col, -1), "Helvetica-Bold"))
    tbl.setStyle(TableStyle(style))
    return tbl


def _info_table(rows: list) -> Table:
    """Two-column key-value info table."""
    s = _styles()
    data = [[Paragraph(r[0], s["bold"]), Paragraph(r[1], s["body"])] for r in rows]
    tbl = Table(data, colWidths=[6*cm, 11*cm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (0, -1), C_LIGHT),
        ("GRID",        (0, 0), (-1, -1), 0.4, C_BORDER),
        ("FONTSIZE",    (0, 0), (-1, -1), 9),
        ("TOPPADDING",  (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return tbl


# ── ROUTES ────────────────────────────────────────────────────

@router.get("/energy")
def energy_report(
    current_user: models.User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    data = (db.query(models.EnergyData)
            .filter(models.EnergyData.user_id == current_user.id)
            .order_by(models.EnergyData.year, models.EnergyData.month)
            .all())

    s = _styles()
    total_kwh  = sum(d.units_kwh for d in data)
    total_cost = sum(d.cost_inr  for d in data)
    total_co2  = total_kwh * EMISSION_FACTOR
    avg_rate   = (total_cost / total_kwh) if total_kwh else 0
    months_cnt = len(data)

    # KPI row
    kpi = _kpi_row([
        ("Total Energy Consumed", f"{total_kwh:,.0f}", "kWh", "#0284c7"),
        ("Total OpEx",            f"\u20b9{total_cost:,.0f}", "INR", "#059669"),
        ("Avg Tariff Rate",       f"\u20b9{avg_rate:.2f}", "/kWh", "#d97706"),
        ("CO\u2082 Emitted",      f"{total_co2/1000:.2f}", "Tonnes", "#475569"),
    ])

    # Organisation info
    org_tbl = _info_table([
        ["Organisation",   current_user.name],
        ["Email",          current_user.email],
        ["Sector",         str(current_user.org_type or "Not Specified")],
        ["Report Period",  f"{months_cnt} months of metered data"],
        ["Report Date",    datetime.now().strftime("%d %B %Y")],
    ])

    # Data table
    rows = [
        [MONTHS_SHORT[d.month], d.year,
         f"{d.units_kwh:,.1f}",
         f"\u20b9{d.cost_inr:,.0f}",
         f"\u20b9{(d.cost_inr/d.units_kwh):.2f}",
         f"{d.units_kwh * EMISSION_FACTOR:,.1f}"]
        for d in data
    ]
    data_tbl = _data_table(
        ["Month", "Year", "Usage (kWh)", "Cost (INR)", "Tariff (INR/kWh)", "CO\u2082 (kg)"],
        rows,
        col_widths=[2.5*cm, 1.8*cm, 3.5*cm, 3.5*cm, 4*cm, 3.2*cm],
        highlight_col=2,
    )

    sections = [
        [Paragraph("Executive Summary", s["h2"]), kpi, Spacer(1, 8)],
        [Paragraph("Organisation Profile", s["h2"]), org_tbl, Spacer(1, 8)],
        [Paragraph("Monthly Energy Ledger", s["h2"]), data_tbl],
    ]

    buf = _build_pdf(
        "Comprehensive Energy Report",
        f"Prepared for: {current_user.name}  |  Period: {months_cnt} months",
        sections,
    )
    return StreamingResponse(buf, media_type="application/pdf",
                             headers={"Content-Disposition": "attachment; filename=energy_report.pdf"})


@router.get("/audit/{audit_id}")
def audit_report(
    audit_id: int,
    current_user: models.User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    audit = db.query(models.Audit).get(audit_id)
    if not audit:
        raise HTTPException(status_code=404, detail="Audit not found")
    if current_user.role == models.UserRole.client and audit.client_id != current_user.id:
        raise HTTPException(status_code=403, detail="Forbidden")

    s = _styles()
    score = audit.efficiency_score or 0
    savings = audit.estimated_savings_inr or 0
    score_color = "#059669" if score >= 80 else ("#d97706" if score >= 60 else "#dc2626")

    kpi = _kpi_row([
        ("Efficiency Score",     str(score),              "/ 100",      score_color),
        ("Estimated Ann. Savings", f"\u20b9{savings:,.0f}", "INR / year", "#059669"),
        ("Audit Status",         audit.status.value.replace("_", " ").title(), "", "#0284c7"),
    ])

    details_tbl = _info_table([
        ["Audit Reference",  f"#{audit.id}"],
        ["Client",           audit.client.name  if audit.client  else "N/A"],
        ["Assigned Auditor", audit.auditor.name if audit.auditor else "Unassigned"],
        ["Date Requested",   audit.created_at.strftime("%d %B %Y") if audit.created_at else "N/A"],
        ["Date Completed",   audit.updated_at.strftime("%d %B %Y") if audit.updated_at else "Pending"],
        ["Efficiency Score", f"{score}/100"],
        ["Estimated Savings",f"\u20b9{savings:,.0f} per annum"],
    ])

    recs_content = [Paragraph("Findings & Recommendations", s["h2"])]
    if audit.recommendations:
        for i, line in enumerate(audit.recommendations.split("\n"), 1):
            if line.strip():
                recs_content.append(
                    Paragraph(f"{i}.  {line.strip()}", s["body"])
                )
    else:
        recs_content.append(Paragraph("No specific recommendations recorded for this audit.", s["body"]))

    sections = [
        [Paragraph("Audit Performance Summary", s["h2"]), kpi, Spacer(1, 8)],
        [Paragraph("Audit Details", s["h2"]), details_tbl, Spacer(1, 8)],
        recs_content,
    ]

    buf = _build_pdf(
        f"Energy Audit Report  \u2014  #{audit_id}",
        f"Client: {audit.client.name if audit.client else 'N/A'}  |  "
        f"Status: {audit.status.value.replace('_',' ').title()}  |  "
        f"Date: {datetime.now().strftime('%d %B %Y')}",
        sections,
    )
    return StreamingResponse(buf, media_type="application/pdf",
                             headers={"Content-Disposition": f"attachment; filename=audit_report_{audit_id}.pdf"})


@router.get("/carbon")
def carbon_report(
    current_user: models.User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    data = (db.query(models.EnergyData)
            .filter(models.EnergyData.user_id == current_user.id)
            .order_by(models.EnergyData.year, models.EnergyData.month)
            .all())

    s = _styles()
    total_kwh  = sum(d.units_kwh  for d in data)
    total_co2  = total_kwh * EMISSION_FACTOR
    tonnes_co2 = total_co2 / 1000
    trees_needed = total_co2 / 21

    kpi = _kpi_row([
        ("Total Energy",      f"{total_kwh:,.0f}",    "kWh",    "#0284c7"),
        ("Total CO\u2082",    f"{total_co2:,.0f}",    "kg",     "#dc2626"),
        ("Carbon Tonnes",     f"{tonnes_co2:.2f}",    "tCO\u2082", "#d97706"),
        ("Offset Trees Req.", f"{trees_needed:,.0f}", "trees",  "#059669"),
    ])

    context_tbl = _info_table([
        ["Emission Factor",    f"{EMISSION_FACTOR} kg CO\u2082/kWh (India CEA Grid Average)"],
        ["Reporting Standard", "GHG Protocol Scope 2 — Location-Based Method"],
        ["Data Source",        "Metered energy consumption records"],
        ["Report Period",      f"{len(data)} months"],
        ["Report Date",        datetime.now().strftime("%d %B %Y")],
    ])

    rows = [
        [MONTHS_SHORT[d.month], d.year,
         f"{d.units_kwh:,.1f}",
         f"{d.units_kwh * EMISSION_FACTOR:,.1f}",
         f"{(d.units_kwh * EMISSION_FACTOR)/1000:.4f}",
         f"{(d.units_kwh * EMISSION_FACTOR)/21:.1f}"]
        for d in data
    ]
    data_tbl = _data_table(
        ["Month", "Year", "Usage (kWh)", "CO\u2082 (kg)", "CO\u2082 (Tonnes)", "Trees to Offset"],
        rows,
        col_widths=[2.2*cm, 1.8*cm, 3.3*cm, 3.2*cm, 3.5*cm, 4*cm],
        highlight_col=3,
    )

    sections = [
        [Paragraph("Carbon Footprint Summary", s["h2"]), kpi, Spacer(1, 8)],
        [Paragraph("Methodology & Context", s["h2"]), context_tbl, Spacer(1, 8)],
        [Paragraph("Monthly Emissions Breakdown", s["h2"]), data_tbl],
    ]

    buf = _build_pdf(
        "Carbon Impact & Sustainability Report",
        f"Prepared for: {current_user.name}  |  GHG Protocol Scope 2  |  {datetime.now().strftime('%B %Y')}",
        sections,
    )
    return StreamingResponse(buf, media_type="application/pdf",
                             headers={"Content-Disposition": "attachment; filename=carbon_report.pdf"})
